import 'org.ssssssss.script.MagicScript'
import 'org.ssssssss.script.MagicScript' as t1
import org.ssssssss.script.MagicScript as t2
import org.ssssssss.script.runtime.RuntimeContext
import 'java.text.*'
import java.io.*;
return
    t1 == MagicScript
    && t2 == t1
    && DateFormat.LONG == 1
    && File::string == 'class java.io.File'
    && RuntimeContext::string == 'class org.ssssssss.script.runtime.RuntimeContext'